export interface ProductWithBoutique {
  id: string;
  /** Generated by migration 0057; absent until it is applied. */
  slug?: string | null;
  boutique_id: string;
  title: string;
  category: string;
  price: number;
  stock: number;
  fabric: string | null;
  color: string | null;
  occasion: string | null;
  image_url: string | null;
  tone: number;
  featured: boolean;
  rating: number;
  reviews_count: number;
  created_at: string;
  /** Units sold on accepted/shipped/delivered orders — maintained by the
   *  triggers in migration 0023, never written by the app. */
  sold_count?: number;
  /** Public Inspire-feed hearts (migration 0020). */
  likes_count?: number;
  /** Buyer-side engagement, all trigger/RPC-maintained (migration 0031). */
  views_count?: number;
  shares_count?: number;
  wishlist_count?: number;
  last_viewed_at?: string | null;
  description?: string | null;
  mrp?: number | null;
  /** Ties this piece to its other colours (migration 0103). Every product
   *  sharing the id is the same piece in a different colour, each with its own
   *  photos, price and stock. Absent until the migration is applied. */
  variant_group_id?: string | null;
  /** Per-size stock, e.g. `{ S: 3, M: 5 }` (migration 0103). NULL/absent means
   *  the sizes share the single pooled `stock`, as every product did before —
   *  nothing was backfilled, so a product converts when its seller next saves
   *  it. `stock` stays the authoritative total either way, kept equal to the
   *  sum of this map by trigger. */
  size_stock?: Record<string, number> | null;
  /** Packed weight in grams (migration 0065). Optional so a project that hasn't
   *  run it still reads products; NULL means "use the boutique default". */
  weight_grams?: number | null;
  sizes?: string[] | null;
  wash_care?: string | null;
  images?: string[] | null;
  /** PDP detail sections (migration 0054). Optional so a project that hasn't
   *  run it yet still reads products — the buyer page hides what's missing. */
  badges?: string[] | null;
  feeding_friendly?: boolean | null;
  feeding_note?: string | null;
  shipping_info?: string | null;
  color_disclaimer?: string | null;
  specs?: ProductSpec[] | null;
  boutique: { name: string; city: string; tone: number } | null;
}

/** One seller-written specification row, shown under the derived ones. */
export interface ProductSpec {
  label: string;
  value: string;
}

// The lifecycle status is declared alongside the generated table types so the
// Supabase client and the app agree on it; re-exported here because every
// consumer already imports its boutique types from this module.
export type { BoutiqueStatus, OrderStatus, PaymentStatus } from '@/types/database';
import type { BoutiqueStatus, OrderStatus, PaymentStatus } from '@/types/database';

/**
 * Human labels for the lifecycle status. Capitalising the raw value is not
 * enough — it would surface `changes_requested` as "Changes_requested".
 */
export const BOUTIQUE_STATUS_LABEL: Record<BoutiqueStatus, string> = {
  draft: 'Setting up',
  pending: 'Awaiting review',
  changes_requested: 'Needs changes',
  approved: 'Approved',
  rejected: 'Rejected',
};

export const WORKING_DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const;

/**
 * A boutique as the app reads it. Every field here is covered by the
 * column-level SELECT grant in migration 0021 — the sensitive ones (GST, bank,
 * review note) live on `BoutiquePrivate` and only arrive via the
 * `boutique_private` RPC, so they can never leak into a buyer-facing payload.
 */
export interface BoutiqueRow {
  id: string;
  owner_id: string;
  name: string;
  slug: string | null;
  city: string;
  area: string;
  description: string;
  tone: number;
  cover_url: string | null;
  logo_url: string | null;
  /**
   * Contact details — present ONLY on a boutique the caller owns (or an admin
   * read). Migration 0073 revoked these three columns from anon/authenticated
   * because they made every seller's mobile number and email bulk-readable with
   * the public anon key; `fetchMyBoutique` merges them back in from
   * `boutique_private()`. Optional rather than nullable on purpose: on a
   * buyer-facing read they are genuinely ABSENT, not null, and the type should
   * say so rather than let a component render `undefined`.
   */
  phone?: string | null;
  instagram: string | null;
  established_year: number | null;
  verified: boolean;
  status: BoutiqueStatus;
  featured: boolean;
  rating: number;
  reviews_count: number;
  followers_count: number;
  positive_rating: number;
  created_at: string;
  /** Shop-wide sales counters (migration 0023), maintained by trigger. */
  units_sold?: number;
  orders_count?: number;

  // Step 1 — boutique information
  owner_name: string;
  // Step 2 — contact
  whatsapp?: string | null;
  email?: string | null;
  // Step 3 — shop address
  address_line: string;
  district: string;
  state: string;
  pincode: string;
  map_url: string | null;
  /**
   * The shop's map pin (migration 0076). Optional on the type because the
   * columns are only selected when the migration has been applied — a link with
   * no coordinates (a shortened maps.app.goo.gl share) leaves these null.
   */
  latitude?: number | null;
  longitude?: number | null;
  // Step 4 — business
  category: string;
  years_in_business: number | null;
  // Step 5 — store settings
  open_time: string;
  close_time: string;
  working_days: string[];
  delivery_available: boolean;
  delivery_areas: string;
  /**
   * What this boutique charges to deliver, and the terms around it. These are
   * the seller's numbers, not the platform's: since migration 0076 the buyer is
   * charged `delivery_charge` per boutique in the bag, waived once that
   * boutique's goods reach `free_delivery_over` where that is set.
   *
   * The ones added in 0076 are optional on the type because the query drops
   * them on a deployment where the migration has not been applied yet.
   */
  delivery_charge: number;
  /**
   * Delivery priced by distance (migration 0077) — the rest of the shop's
   * district, its state, and the rest of India. `null` means the shop does not
   * deliver that far; `undefined` means the columns were not selected, and the
   * local rate stands in.
   */
  delivery_charge_district?: number | null;
  delivery_charge_state?: number | null;
  delivery_charge_national?: number | null;
  free_delivery_over?: number;
  /**
   * How long this shop takes to pack an order, and how long buyers have to send
   * it back (migration 0078). Both were platform constants the buyer read as
   * facts about the shop. `return_window_days` is the GOODWILL window only —
   * fault claims are always accepted for 30 days. Optional on the type because
   * the query drops them where 0078 has not been applied.
   */
  dispatch_days_min?: number;
  dispatch_days_max?: number;
  return_window_days?: number;
  /* `cod_enabled`, `cod_fee` and `cod_max_order` still exist as columns but are
   * no longer selected or written as a seller choice: cash on delivery was
   * withdrawn platform-wide (migration 0085), which forces the flag off for
   * every shop. See src/pages/seller/Settings.tsx. */
  online_payment_enabled: boolean;
  // Step 7 — submission
  onboarding_step: number;
  onboarding_complete: boolean;
  submitted_at: string | null;
  reviewed_at: string | null;
  // Notification preferences
  notify_orders: boolean;
  notify_messages: boolean;
  notify_promotions: boolean;
}

/** The withheld columns, readable by the owner or an admin only. */
export interface BoutiquePrivate {
  gst_number: string | null;
  business_reg_number: string | null;
  bank_account_name: string | null;
  bank_account_number: string | null;
  bank_ifsc: string | null;
  upi_id: string | null;
  review_note: string | null;
  /** Penny-drop state of the payout account (migration 0027). */
  payout_verification_status?: 'unverified' | 'pending' | 'verified' | 'failed' | null;
  payout_verification_note?: string | null;
  /**
   * Shop contact details (migration 0073). These used to be on the public
   * column grant, which made every seller's mobile number and email
   * bulk-readable with the anon key; they are owner-or-admin only now.
   */
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
}

export interface OrderWithDetails {
  id: string;
  order_number: string;
  buyer_id: string | null;
  boutique_id: string;
  status: OrderStatus;
  total: number;
  created_at: string;
  /** When the boutique moved this order into each stage (migration 0042). */
  accepted_at?: string | null;
  shipped_at?: string | null;
  delivered_at?: string | null;
  guest_name: string | null;
  guest_phone: string | null;
  guest_city: string | null;
  guest_address?: string | null;
  guest_pincode?: string | null;
  payment_id?: string | null;
  refunded?: boolean;
  channel?: 'online' | 'offline';
  payment_method?: string | null;
  /** Settlement state. Always 'paid' on a new order — every one is prepaid
   *  (migration 0085); 'pending' only survives on a legacy cash order. */
  payment_status?: PaymentStatus;
  paid_at?: string | null;
  /** Cash-handling fee. Always 0 except on a pre-0085 cash order, where it is
   *  part of what the buyer paid and so part of what its invoice must show. */
  cod_fee?: number;
  /** Delivery fee on this order (cart-level, so it lands on the first order). */
  shipping_fee?: number;
  /** Platform-funded coupon discount (migration 0053). Not deducted from
   *  `total` — the seller is paid in full — but it is off what the buyer owes. */
  platform_discount?: number;
  /** Migration 0097. Razorpay's own reference for the refund, and where it got
   *  to. Optional for the same reason as the 0063 columns below: the SELECT
   *  drops them when the migration has not been applied yet. A `refunded` row
   *  with no `refund_id` was flagged by hand before real refunds existed. */
  refund_id?: string | null;
  refund_amount?: number | null;
  refund_status?: 'pending' | 'processed' | 'failed' | null;
  cancelled_at?: string | null;
  cancel_reason?: string | null;
  /** Migration 0063. Optional because the SELECT falls back to a column list
   *  without them when the migration has not been applied yet. */
  packed_at?: string | null;
  /** Only ever set by a courier webhook, which does not exist yet — so the
   *  buyer's "Out for delivery" stage stays dim rather than being faked. */
  out_for_delivery_at?: string | null;
  /** The buyer said it never arrived. Blocks the payout sweep until resolved. */
  delivery_disputed?: boolean;
  delivery_disputed_at?: string | null;
  buyer: { full_name: string; phone: string | null; city: string | null } | null;
  boutique: { name: string; tone: number } | null;
  items: {
    id: string;
    product_id: string | null;
    title: string;
    price: number;
    qty: number;
    size: string | null;
    color: string | null;
    /**
     * The catalogue row this line was bought from, joined in for its photo.
     * `order_items` deliberately snapshots the title and price at purchase
     * time but keeps no image, so without this join every order screen could
     * only paint a tinted placeholder. Null when the product has since been
     * deleted (or is not readable), which is why the placeholder stays.
     */
    product?: { image_url: string | null; tone: number } | null;
  }[];
}

export interface ConversationWithPeer {
  id: string;
  buyer_id: string;
  boutique_id: string;
  created_at: string;
  buyer_name: string;
  boutique_name: string;
  boutique_tone: number;
  last_message: string;
  last_message_at: string | null;
  unread: number;
}

export interface MessageRow {
  id: string;
  conversation_id: string;
  sender_id: string;
  body: string;
  created_at: string;
}
